package com.yzn.transaction_consumer.model.enums;

public enum LaunderingType {
    NORMAL_CASH_DEPOSITS,
    NORMAL_FAN_OUT,
    NORMAL_SMALL_FAN_OUT,
    NORMAL_FAN_IN,
    NORMAL_GROUP,
    NORMAL_CASH_WITHDRAWAL,
    NORMAL_PERIODICAL,
    NORMAL_FOWARD,
    NORMAL_MUTUAL,
    NORMAL_PLUS_MUTUAL,
    SMURFING,
    NORMAL_SINGLE_LARGE,
    CASH_WITHDRAWAL,
    BEHAVIOURAL_CHANGE_2,
    STRUCTURING,
    BEHAVIOURAL_CHANGE_1,
    LAYERED_FAN_IN,
    LAYERED_FAN_OUT,
    SCATTER_GATHER,
    CYCLE,
    FAN_IN,
    STACKED_BIPARTITE,
    OVER_INVOICING,
    DEPOSIT_SEND,
    SINGLE_LARGE,
    BIPARTITE,
    GATHER_SCATTER,
    FAN_OUT

}
